/**
 * Route/viewport pairs that overflowed horizontally before the redesign.
 * Regenerate with `node e2e/write-layout-baseline.mjs <results.json>`.
 * Must be empty when the redesign is complete.
 */
export const knownLayoutOverflow = new Set<string>([
  "desktop /overview",
  "desktop /threat-hunting/analytics",
  "mobile /administration/audit",
  "mobile /administration/enterprise",
  "mobile /administration/integrations",
  "mobile /administration/users",
  "mobile /alerts/assigned",
  "mobile /alerts/list",
  "mobile /alerts/overview",
  "mobile /assets/devices",
  "mobile /assets/identities",
  "mobile /automation/approvals",
  "mobile /automation/builder",
  "mobile /automation/playbooks",
  "mobile /cloud-posture",
  "mobile /compliance",
  "mobile /data-security",
  "mobile /email-security",
  "mobile /incidents/assigned",
  "mobile /incidents/list",
  "mobile /incidents/overview",
  "mobile /investigate",
  "mobile /investigate/saved",
  "mobile /knowledge-base/documentation",
  "mobile /knowledge-base/procedures",
  "mobile /knowledge-base/reports",
  "mobile /knowledge-base/trainings",
  "mobile /on-call",
  "mobile /overview",
  "mobile /profile",
  "mobile /profile/notifications",
  "mobile /profile/preferences",
  "mobile /profile/security",
  "mobile /purple-team",
  "mobile /threat-hunting/analytics",
  "mobile /threat-hunting/detections",
  "mobile /threat-hunting/hunts",
  "mobile /threat-hunting/map",
  "mobile /threat-intelligence",
  "mobile /threat-intelligence/actors",
  "mobile /threat-intelligence/attack-surface",
  "mobile /threat-intelligence/dark-web",
  "mobile /threat-intelligence/feeds",
  "mobile /vulnerabilities",
  "mobile /vulnerabilities/event-timeline",
  "mobile /vulnerabilities/exposure",
  "mobile /vulnerabilities/findings",
  "mobile /vulnerabilities/inventories",
  "mobile /vulnerabilities/recommendations",
  "mobile /vulnerabilities/remediations",
  "mobile /vulnerabilities/weaknesses",
  "mobile /vulnerabilities/work",
  "mobile detail:/administration/users",
  "mobile detail:/alerts/list",
  "mobile detail:/incidents/list",
  "tablet /investigate/saved",
  "tablet /overview",
]);
