/** Every UI route in the portal. Detail routes are reached from their lists. */
export const publicRoutes = [
  "/login",
  "/register",
  "/forgot-password",
  "/privacy",
  "/terms",
  "/401",
  "/403",
  "/404",
  "/503",
  "/error",
] as const;

export const adminRoutes = [
  "/overview",
  "/alerts/overview",
  "/alerts/list",
  "/alerts/assigned",
  "/incidents/overview",
  "/incidents/list",
  "/incidents/assigned",
  "/email-security",
  "/investigate",
  "/investigate/saved",
  "/assets/devices",
  "/assets/identities",
  "/cloud-posture",
  "/vulnerabilities",
  "/vulnerabilities/findings",
  "/vulnerabilities/exposure",
  "/vulnerabilities/work",
  "/vulnerabilities/weaknesses",
  "/vulnerabilities/recommendations",
  "/vulnerabilities/remediations",
  "/vulnerabilities/inventories",
  "/vulnerabilities/event-timeline",
  "/data-security",
  "/threat-hunting/hunts",
  "/threat-hunting/detections",
  "/threat-hunting/analytics",
  "/threat-hunting/map",
  "/purple-team",
  "/threat-intelligence",
  "/threat-intelligence/actors",
  "/threat-intelligence/dark-web",
  "/threat-intelligence/attack-surface",
  "/threat-intelligence/feeds",
  "/automation/playbooks",
  "/automation/builder",
  "/automation/approvals",
  "/compliance",
  "/knowledge-base/documentation",
  "/knowledge-base/procedures",
  "/knowledge-base/reports",
  "/knowledge-base/trainings",
  "/administration/users",
  "/administration/integrations",
  "/administration/enterprise",
  "/administration/audit",
  "/on-call",
  "/profile",
  "/profile/preferences",
  "/profile/security",
  "/profile/notifications",
] as const;

/** List page → link pattern for its detail route. */
export const detailRoutes = [
  { from: "/alerts/list", link: /^\/alerts\/(?!list|assigned|overview)[^/?#]+$/ },
  { from: "/incidents/list", link: /^\/incidents\/(?!list|assigned|overview)[^/?#]+$/ },
  { from: "/administration/users", link: /^\/administration\/users\/[^/?#]+$/ },
] as const;

/** Redirect-only routes and where they land. */
export const redirectRoutes = [
  { from: "/alerts", to: "/alerts/overview" },
  { from: "/incidents", to: "/incidents/overview" },
  { from: "/automation", to: "/automation/playbooks" },
  { from: "/phishing", to: "/email-security" },
  { from: "/cloud-posture/findings", to: "/cloud-posture" },
] as const;
