'use client'

import type { IconType } from 'react-icons'
import {
  IoAddOutline,
  IoAlertCircleOutline,
  IoAnalyticsOutline,
  IoArrowBackOutline,
  IoArrowForwardOutline,
  IoBugOutline,
  IoBusinessOutline,
  IoCalendarOutline,
  IoChatbubbleEllipsesOutline,
  IoCheckmarkCircleOutline,
  IoCheckmarkDoneOutline,
  IoChevronBackOutline,
  IoChevronDownOutline,
  IoChevronForwardOutline,
  IoCloseCircleOutline,
  IoCloseOutline,
  IoCloudOutline,
  IoCreateOutline,
  IoDesktopOutline,
  IoDocumentTextOutline,
  IoEyeOutline,
  IoFingerPrintOutline,
  IoGlobeOutline,
  IoHardwareChipOutline,
  IoHelpCircleOutline,
  IoInformationCircleOutline,
  IoLaptopOutline,
  IoLogoLinkedin,
  IoLogoGithub,
  IoLogoGoogle,
  IoPaperPlaneOutline,
  IoLibraryOutline,
  IoMailOutline,
  IoMenuOutline,
  IoMoonOutline,
  IoNotificationsOutline,
  IoPersonCircleOutline,
  IoPhonePortraitOutline,
  IoPieChartOutline,
  IoPulseOutline,
  IoReloadOutline,
  IoSearchOutline,
  IoServerOutline,
  IoSettingsOutline,
  IoShieldCheckmarkOutline,
  IoSunnyOutline,
  IoTrendingDownOutline,
  IoTrendingUpOutline,
  IoWarningOutline,
} from 'react-icons/io5'

/** Ionicons (outline) — names match Ionicons web component `name` strings (e.g. search-outline). */
const ICONS: Record<string, IconType> = {
  'add-outline': IoAddOutline,
  'alert-circle-outline': IoAlertCircleOutline,
  'analytics-outline': IoAnalyticsOutline,
  'arrow-back-outline': IoArrowBackOutline,
  'arrow-forward-outline': IoArrowForwardOutline,
  'bug-outline': IoBugOutline,
  'business-outline': IoBusinessOutline,
  'calendar-outline': IoCalendarOutline,
  'chatbubble-ellipses-outline': IoChatbubbleEllipsesOutline,
  'checkmark-circle-outline': IoCheckmarkCircleOutline,
  'checkmark-done-outline': IoCheckmarkDoneOutline,
  'chevron-back-outline': IoChevronBackOutline,
  'chevron-down-outline': IoChevronDownOutline,
  'chevron-forward-outline': IoChevronForwardOutline,
  'close-circle-outline': IoCloseCircleOutline,
  'close-outline': IoCloseOutline,
  'cloud-outline': IoCloudOutline,
  'create-outline': IoCreateOutline,
  'desktop-outline': IoDesktopOutline,
  'document-text-outline': IoDocumentTextOutline,
  'eye-outline': IoEyeOutline,
  'finger-print-outline': IoFingerPrintOutline,
  'hardware-chip-outline': IoHardwareChipOutline,
  'information-circle-outline': IoInformationCircleOutline,
  'logo-github': IoLogoGithub,
  'logo-google': IoLogoGoogle,
  'logo-linkedin': IoLogoLinkedin,
  'paper-plane-outline': IoPaperPlaneOutline,
  'library-outline': IoLibraryOutline,
  'laptop-outline': IoLaptopOutline,
  'mail-outline': IoMailOutline,
  'menu-outline': IoMenuOutline,
  'moon-outline': IoMoonOutline,
  'notifications-outline': IoNotificationsOutline,
  'person-circle-outline': IoPersonCircleOutline,
  'phone-portrait-outline': IoPhonePortraitOutline,
  'pie-chart-outline': IoPieChartOutline,
  'pulse-outline': IoPulseOutline,
  'reload-outline': IoReloadOutline,
  'search-outline': IoSearchOutline,
  'server-outline': IoServerOutline,
  'settings-outline': IoSettingsOutline,
  'shield-checkmark-outline': IoShieldCheckmarkOutline,
  'sunny-outline': IoSunnyOutline,
  'trending-down-outline': IoTrendingDownOutline,
  'trending-up-outline': IoTrendingUpOutline,
  'warning-outline': IoWarningOutline,
  'globe-outline': IoGlobeOutline,
}

interface IconProps {
  name: string
  className?: string
  title?: string
}

export default function Icon({ name, className = '', title }: IconProps) {
  const Cmp = ICONS[name] ?? IoHelpCircleOutline
  return <Cmp className={`inline-block ${className}`} aria-hidden={title ? undefined : true} title={title} />
}

export { ICONS }
