export type DeviceCategory = "endpoint" | "server" | "network" | "iot";

export type DeviceStatus = "online" | "offline" | "at-risk" | "pending";

export type DevicePlatform =
  | "Windows"
  | "macOS"
  | "Linux"
  | "iOS"
  | "Android"
  | "Cisco IOS"
  | "FortiOS"
  | "Firmware";

export type AssetDevice = {
  id: string;
  name: string;
  hostname: string;
  category: DeviceCategory;
  platform: DevicePlatform;
  status: DeviceStatus;
  owner: string;
  department: string;
  ipAddress: string;
  location: string;
  agentInstalled: boolean;
  isolated: boolean;
  vulnerabilityCount: number;
  lastSeenLabel: string;
  lastSeenValue: number;
  riskScore: number;
};

export const deviceCategoryLabels: Record<DeviceCategory, string> = {
  endpoint: "Endpoint",
  server: "Server",
  network: "Network",
  iot: "IoT",
};

export const deviceStatusLabels: Record<DeviceStatus, string> = {
  online: "Online",
  offline: "Offline",
  "at-risk": "At risk",
  pending: "Pending",
};

export const deviceStatusColors: Record<DeviceStatus, string> = {
  online: "#22c55e",
  offline: "#71717a",
  "at-risk": "#f59e0b",
  pending: "#3b82f6",
};

export type DeviceListStat = {
  title: string;
  value: string;
  delta: number;
  context: string;
  /** When true, a falling trend is healthy (shown in green). */
  preferLower: boolean;
};

export const assetDevices: AssetDevice[] = [
  // Endpoints (8)
  {
    id: "dev-ep-01",
    name: "Finance Laptop",
    hostname: "LAP-FIN-0142",
    category: "endpoint",
    platform: "Windows",
    status: "online",
    owner: "Liza Harlan",
    department: "Finance",
    ipAddress: "10.12.4.88",
    location: "HQ · Floor 3",
    agentInstalled: true,
    isolated: false,
    vulnerabilityCount: 2,
    lastSeenLabel: "2 min ago",
    lastSeenValue: 202607241430,
    riskScore: 18,
  },
  {
    id: "dev-ep-02",
    name: "SOC Workstation",
    hostname: "WS-SOC-0007",
    category: "endpoint",
    platform: "Windows",
    status: "online",
    owner: "Kabir Sethi",
    department: "Security",
    ipAddress: "10.12.8.21",
    location: "HQ · SOC",
    agentInstalled: true,
    isolated: false,
    vulnerabilityCount: 0,
    lastSeenLabel: "Just now",
    lastSeenValue: 202607241445,
    riskScore: 8,
  },
  {
    id: "dev-ep-03",
    name: "Design MacBook",
    hostname: "MBP-DES-0331",
    category: "endpoint",
    platform: "macOS",
    status: "at-risk",
    owner: "Robyn Carr",
    department: "Product",
    ipAddress: "10.12.6.54",
    location: "Remote · SF",
    agentInstalled: true,
    isolated: true,
    vulnerabilityCount: 11,
    lastSeenLabel: "1 hour ago",
    lastSeenValue: 202607241345,
    riskScore: 72,
  },
  {
    id: "dev-ep-04",
    name: "Field Tablet",
    hostname: "TAB-OPS-0190",
    category: "endpoint",
    platform: "iOS",
    status: "offline",
    owner: "Farid Tamin",
    department: "Operations",
    ipAddress: "10.40.2.17",
    location: "Field · Austin",
    agentInstalled: false,
    isolated: false,
    vulnerabilityCount: 5,
    lastSeenLabel: "3 days ago",
    lastSeenValue: 202607211100,
    riskScore: 61,
  },
  {
    id: "dev-ep-05",
    name: "HR Desktop",
    hostname: "DESK-HR-0088",
    category: "endpoint",
    platform: "Windows",
    status: "online",
    owner: "Maya Rao",
    department: "People",
    ipAddress: "10.12.5.41",
    location: "HQ · Floor 2",
    agentInstalled: true,
    isolated: false,
    vulnerabilityCount: 1,
    lastSeenLabel: "5 min ago",
    lastSeenValue: 202607241440,
    riskScore: 21,
  },
  {
    id: "dev-ep-06",
    name: "Sales Ultrabook",
    hostname: "LAP-SAL-0220",
    category: "endpoint",
    platform: "Windows",
    status: "offline",
    owner: "Brendan Murphy",
    department: "Sales",
    ipAddress: "10.12.9.77",
    location: "Remote · Chicago",
    agentInstalled: true,
    isolated: false,
    vulnerabilityCount: 3,
    lastSeenLabel: "18 hours ago",
    lastSeenValue: 202607232045,
    riskScore: 39,
  },
  {
    id: "dev-ep-07",
    name: "Contractor Chromebook",
    hostname: "CB-EXT-0044",
    category: "endpoint",
    platform: "Linux",
    status: "pending",
    owner: "Vendor Access",
    department: "Contractors",
    ipAddress: "10.70.3.15",
    location: "Remote · VPN",
    agentInstalled: false,
    isolated: false,
    vulnerabilityCount: 7,
    lastSeenLabel: "Never",
    lastSeenValue: 0,
    riskScore: 55,
  },
  {
    id: "dev-ep-08",
    name: "Exec iPhone",
    hostname: "IPH-EXE-0003",
    category: "endpoint",
    platform: "iOS",
    status: "online",
    owner: "Gareth Doyle",
    department: "Executive",
    ipAddress: "10.12.11.9",
    location: "HQ · Floor 5",
    agentInstalled: true,
    isolated: false,
    vulnerabilityCount: 0,
    lastSeenLabel: "9 min ago",
    lastSeenValue: 202607241436,
    riskScore: 16,
  },
  {
    id: "dev-ep-09",
    name: "Legal Laptop",
    hostname: "LAP-LEG-0056",
    category: "endpoint",
    platform: "Windows",
    status: "online",
    owner: "Sofia Ahmed",
    department: "Legal",
    ipAddress: "10.12.7.33",
    location: "HQ · Floor 4",
    agentInstalled: true,
    isolated: false,
    vulnerabilityCount: 1,
    lastSeenLabel: "12 min ago",
    lastSeenValue: 202607241433,
    riskScore: 17,
  },
  {
    id: "dev-ep-10",
    name: "Data Science Rig",
    hostname: "WS-DATA-0021",
    category: "endpoint",
    platform: "Linux",
    status: "online",
    owner: "Tia West",
    department: "Data",
    ipAddress: "10.12.10.14",
    location: "HQ · Floor 3",
    agentInstalled: true,
    isolated: false,
    vulnerabilityCount: 3,
    lastSeenLabel: "6 min ago",
    lastSeenValue: 202607241439,
    riskScore: 26,
  },
  {
    id: "dev-ep-11",
    name: "Support Desktop",
    hostname: "DESK-SUP-0102",
    category: "endpoint",
    platform: "Windows",
    status: "online",
    owner: "Chloe Park",
    department: "Support",
    ipAddress: "10.12.5.88",
    location: "HQ · Floor 2",
    agentInstalled: true,
    isolated: false,
    vulnerabilityCount: 2,
    lastSeenLabel: "3 min ago",
    lastSeenValue: 202607241442,
    riskScore: 19,
  },
  {
    id: "dev-ep-12",
    name: "QA Test Bench",
    hostname: "WS-QA-0033",
    category: "endpoint",
    platform: "Linux",
    status: "offline",
    owner: "Colin Okon",
    department: "Engineering",
    ipAddress: "10.12.10.61",
    location: "HQ · Lab",
    agentInstalled: true,
    isolated: false,
    vulnerabilityCount: 4,
    lastSeenLabel: "1 day ago",
    lastSeenValue: 202607231400,
    riskScore: 34,
  },
  {
    id: "dev-ep-13",
    name: "Marketing MacBook",
    hostname: "MBP-MKT-0118",
    category: "endpoint",
    platform: "macOS",
    status: "online",
    owner: "Jules Hart",
    department: "Marketing",
    ipAddress: "10.12.6.92",
    location: "Remote · NYC",
    agentInstalled: true,
    isolated: false,
    vulnerabilityCount: 1,
    lastSeenLabel: "28 min ago",
    lastSeenValue: 202607241417,
    riskScore: 15,
  },
  {
    id: "dev-ep-14",
    name: "IR Field Laptop",
    hostname: "LAP-IR-0015",
    category: "endpoint",
    platform: "Windows",
    status: "online",
    owner: "Maya Rao",
    department: "Security",
    ipAddress: "10.12.8.45",
    location: "HQ · SOC",
    agentInstalled: true,
    isolated: false,
    vulnerabilityCount: 0,
    lastSeenLabel: "1 min ago",
    lastSeenValue: 202607241444,
    riskScore: 9,
  },
  {
    id: "dev-ep-15",
    name: "Payroll Workstation",
    hostname: "DESK-FIN-0071",
    category: "endpoint",
    platform: "Windows",
    status: "at-risk",
    owner: "Sienna Light",
    department: "Finance",
    ipAddress: "10.12.4.29",
    location: "HQ · Floor 3",
    agentInstalled: true,
    isolated: false,
    vulnerabilityCount: 8,
    lastSeenLabel: "44 min ago",
    lastSeenValue: 202607241401,
    riskScore: 66,
  },
  {
    id: "dev-ep-16",
    name: "Sales Android",
    hostname: "AND-SAL-0064",
    category: "endpoint",
    platform: "Android",
    status: "online",
    owner: "Cody Crowe",
    department: "Sales",
    ipAddress: "10.40.3.52",
    location: "Remote · Toronto",
    agentInstalled: true,
    isolated: false,
    vulnerabilityCount: 2,
    lastSeenLabel: "19 min ago",
    lastSeenValue: 202607241426,
    riskScore: 23,
  },
  // Servers (9)
  {
    id: "dev-srv-01",
    name: "Auth Primary",
    hostname: "srv-auth-01",
    category: "server",
    platform: "Linux",
    status: "online",
    owner: "Platform Team",
    department: "Infrastructure",
    ipAddress: "10.0.1.10",
    location: "AWS · us-east-1",
    agentInstalled: true,
    isolated: false,
    vulnerabilityCount: 4,
    lastSeenLabel: "Just now",
    lastSeenValue: 202607241445,
    riskScore: 12,
  },
  {
    id: "dev-srv-02",
    name: "SIEM Collector",
    hostname: "srv-siem-02",
    category: "server",
    platform: "Linux",
    status: "online",
    owner: "Detection Engineering",
    department: "Security",
    ipAddress: "10.0.2.44",
    location: "DC · Rack B12",
    agentInstalled: true,
    isolated: false,
    vulnerabilityCount: 2,
    lastSeenLabel: "1 min ago",
    lastSeenValue: 202607241444,
    riskScore: 15,
  },
  {
    id: "dev-srv-03",
    name: "File Share East",
    hostname: "srv-fs-east",
    category: "server",
    platform: "Windows",
    status: "at-risk",
    owner: "IT Ops",
    department: "Infrastructure",
    ipAddress: "10.0.3.18",
    location: "DC · Rack A04",
    agentInstalled: true,
    isolated: true,
    vulnerabilityCount: 14,
    lastSeenLabel: "12 min ago",
    lastSeenValue: 202607241433,
    riskScore: 68,
  },
  {
    id: "dev-srv-04",
    name: "Build Runner",
    hostname: "srv-ci-07",
    category: "server",
    platform: "Linux",
    status: "pending",
    owner: "DevOps",
    department: "Engineering",
    ipAddress: "10.0.5.92",
    location: "GCP · us-central1",
    agentInstalled: false,
    isolated: false,
    vulnerabilityCount: 6,
    lastSeenLabel: "Never",
    lastSeenValue: 0,
    riskScore: 45,
  },
  {
    id: "dev-srv-05",
    name: "Backup Vault",
    hostname: "srv-bkp-03",
    category: "server",
    platform: "Linux",
    status: "online",
    owner: "IT Ops",
    department: "Infrastructure",
    ipAddress: "10.0.4.30",
    location: "DC · Rack C02",
    agentInstalled: true,
    isolated: false,
    vulnerabilityCount: 1,
    lastSeenLabel: "3 min ago",
    lastSeenValue: 202607241442,
    riskScore: 19,
  },
  {
    id: "dev-srv-06",
    name: "API Gateway",
    hostname: "srv-api-gw-01",
    category: "server",
    platform: "Linux",
    status: "online",
    owner: "Platform Team",
    department: "Engineering",
    ipAddress: "10.0.1.22",
    location: "AWS · us-east-1",
    agentInstalled: true,
    isolated: false,
    vulnerabilityCount: 2,
    lastSeenLabel: "Just now",
    lastSeenValue: 202607241445,
    riskScore: 13,
  },
  {
    id: "dev-srv-07",
    name: "Data Warehouse",
    hostname: "srv-dwh-02",
    category: "server",
    platform: "Linux",
    status: "online",
    owner: "Data Platform",
    department: "Data",
    ipAddress: "10.0.6.15",
    location: "GCP · us-central1",
    agentInstalled: true,
    isolated: false,
    vulnerabilityCount: 3,
    lastSeenLabel: "2 min ago",
    lastSeenValue: 202607241443,
    riskScore: 20,
  },
  {
    id: "dev-srv-08",
    name: "Legacy ERP Host",
    hostname: "srv-erp-legacy",
    category: "server",
    platform: "Windows",
    status: "at-risk",
    owner: "IT Ops",
    department: "Finance",
    ipAddress: "10.0.3.40",
    location: "DC · Rack A08",
    agentInstalled: true,
    isolated: false,
    vulnerabilityCount: 17,
    lastSeenLabel: "9 min ago",
    lastSeenValue: 202607241436,
    riskScore: 81,
  },
  {
    id: "dev-srv-09",
    name: "Mail Relay",
    hostname: "srv-mail-01",
    category: "server",
    platform: "Linux",
    status: "online",
    owner: "IT Ops",
    department: "Infrastructure",
    ipAddress: "10.0.2.11",
    location: "DC · Rack B03",
    agentInstalled: true,
    isolated: false,
    vulnerabilityCount: 1,
    lastSeenLabel: "5 min ago",
    lastSeenValue: 202607241440,
    riskScore: 16,
  },
  // Network (6)
  {
    id: "dev-net-01",
    name: "Core Switch A",
    hostname: "sw-core-a",
    category: "network",
    platform: "Cisco IOS",
    status: "online",
    owner: "Network Ops",
    department: "Infrastructure",
    ipAddress: "10.0.0.1",
    location: "DC · MDF",
    agentInstalled: false,
    isolated: false,
    vulnerabilityCount: 3,
    lastSeenLabel: "4 min ago",
    lastSeenValue: 202607241441,
    riskScore: 22,
  },
  {
    id: "dev-net-02",
    name: "Edge Firewall",
    hostname: "fw-edge-01",
    category: "network",
    platform: "FortiOS",
    status: "online",
    owner: "Network Ops",
    department: "Security",
    ipAddress: "10.0.0.2",
    location: "DC · Perimeter",
    agentInstalled: false,
    isolated: false,
    vulnerabilityCount: 1,
    lastSeenLabel: "Just now",
    lastSeenValue: 202607241445,
    riskScore: 14,
  },
  {
    id: "dev-net-03",
    name: "Branch AP Cluster",
    hostname: "ap-branch-sea",
    category: "network",
    platform: "Firmware",
    status: "offline",
    owner: "Network Ops",
    department: "Infrastructure",
    ipAddress: "10.55.1.8",
    location: "Branch · Seattle",
    agentInstalled: false,
    isolated: false,
    vulnerabilityCount: 8,
    lastSeenLabel: "6 hours ago",
    lastSeenValue: 202607240845,
    riskScore: 54,
  },
  {
    id: "dev-net-04",
    name: "VPN Concentrator",
    hostname: "vpn-hub-01",
    category: "network",
    platform: "FortiOS",
    status: "online",
    owner: "Network Ops",
    department: "Security",
    ipAddress: "10.0.0.5",
    location: "DC · Perimeter",
    agentInstalled: false,
    isolated: false,
    vulnerabilityCount: 2,
    lastSeenLabel: "2 min ago",
    lastSeenValue: 202607241443,
    riskScore: 19,
  },
  {
    id: "dev-net-05",
    name: "Core Switch B",
    hostname: "sw-core-b",
    category: "network",
    platform: "Cisco IOS",
    status: "online",
    owner: "Network Ops",
    department: "Infrastructure",
    ipAddress: "10.0.0.3",
    location: "DC · MDF",
    agentInstalled: false,
    isolated: false,
    vulnerabilityCount: 2,
    lastSeenLabel: "7 min ago",
    lastSeenValue: 202607241438,
    riskScore: 21,
  },
  {
    id: "dev-net-06",
    name: "Branch Router Austin",
    hostname: "rtr-branch-aus",
    category: "network",
    platform: "Cisco IOS",
    status: "at-risk",
    owner: "Network Ops",
    department: "Infrastructure",
    ipAddress: "10.55.2.1",
    location: "Branch · Austin",
    agentInstalled: false,
    isolated: false,
    vulnerabilityCount: 7,
    lastSeenLabel: "33 min ago",
    lastSeenValue: 202607241412,
    riskScore: 63,
  },
  // IoT (9)
  {
    id: "dev-iot-01",
    name: "Lobby Badge Reader",
    hostname: "iot-badge-01",
    category: "iot",
    platform: "Firmware",
    status: "online",
    owner: "Facilities",
    department: "Facilities",
    ipAddress: "10.90.1.12",
    location: "HQ · Lobby",
    agentInstalled: false,
    isolated: false,
    vulnerabilityCount: 2,
    lastSeenLabel: "8 min ago",
    lastSeenValue: 202607241437,
    riskScore: 31,
  },
  {
    id: "dev-iot-02",
    name: "HVAC Controller",
    hostname: "iot-hvac-04",
    category: "iot",
    platform: "Firmware",
    status: "at-risk",
    owner: "Facilities",
    department: "Facilities",
    ipAddress: "10.90.2.40",
    location: "HQ · Basement",
    agentInstalled: false,
    isolated: true,
    vulnerabilityCount: 9,
    lastSeenLabel: "25 min ago",
    lastSeenValue: 202607241420,
    riskScore: 79,
  },
  {
    id: "dev-iot-03",
    name: "Conference Cam",
    hostname: "iot-cam-cr3",
    category: "iot",
    platform: "Android",
    status: "online",
    owner: "IT Ops",
    department: "Operations",
    ipAddress: "10.90.3.22",
    location: "HQ · Conf 3",
    agentInstalled: false,
    isolated: false,
    vulnerabilityCount: 1,
    lastSeenLabel: "15 min ago",
    lastSeenValue: 202607241430,
    riskScore: 27,
  },
  {
    id: "dev-iot-04",
    name: "Smart Lock East",
    hostname: "iot-lock-e2",
    category: "iot",
    platform: "Firmware",
    status: "online",
    owner: "Facilities",
    department: "Facilities",
    ipAddress: "10.90.1.44",
    location: "HQ · East Wing",
    agentInstalled: false,
    isolated: false,
    vulnerabilityCount: 2,
    lastSeenLabel: "11 min ago",
    lastSeenValue: 202607241434,
    riskScore: 33,
  },
  {
    id: "dev-iot-05",
    name: "Printer Fleet Hub",
    hostname: "iot-prn-hub",
    category: "iot",
    platform: "Firmware",
    status: "at-risk",
    owner: "IT Ops",
    department: "Operations",
    ipAddress: "10.90.4.8",
    location: "HQ · Print Room",
    agentInstalled: false,
    isolated: false,
    vulnerabilityCount: 10,
    lastSeenLabel: "40 min ago",
    lastSeenValue: 202607241405,
    riskScore: 74,
  },
  {
    id: "dev-iot-06",
    name: "Parking Gate Sensor",
    hostname: "iot-gate-01",
    category: "iot",
    platform: "Firmware",
    status: "offline",
    owner: "Facilities",
    department: "Facilities",
    ipAddress: "10.90.8.3",
    location: "Garage · Level P1",
    agentInstalled: false,
    isolated: false,
    vulnerabilityCount: 4,
    lastSeenLabel: "2 days ago",
    lastSeenValue: 202607221200,
    riskScore: 48,
  },
  {
    id: "dev-iot-07",
    name: "Server Room Sensor",
    hostname: "iot-env-sr1",
    category: "iot",
    platform: "Firmware",
    status: "online",
    owner: "Facilities",
    department: "Facilities",
    ipAddress: "10.90.5.6",
    location: "DC · Server room",
    agentInstalled: false,
    isolated: false,
    vulnerabilityCount: 1,
    lastSeenLabel: "5 min ago",
    lastSeenValue: 202607241440,
    riskScore: 20,
  },
  {
    id: "dev-iot-08",
    name: "Digital Signage Hub",
    hostname: "iot-sign-lby",
    category: "iot",
    platform: "Android",
    status: "online",
    owner: "IT Ops",
    department: "Operations",
    ipAddress: "10.90.6.12",
    location: "HQ · Lobby",
    agentInstalled: false,
    isolated: false,
    vulnerabilityCount: 3,
    lastSeenLabel: "13 min ago",
    lastSeenValue: 202607241432,
    riskScore: 35,
  },
  {
    id: "dev-iot-09",
    name: "Warehouse Scanner Dock",
    hostname: "iot-scan-wh2",
    category: "iot",
    platform: "Firmware",
    status: "offline",
    owner: "Operations",
    department: "Operations",
    ipAddress: "10.90.7.28",
    location: "Warehouse · Dock 2",
    agentInstalled: false,
    isolated: false,
    vulnerabilityCount: 5,
    lastSeenLabel: "12 hours ago",
    lastSeenValue: 202607240245,
    riskScore: 44,
  },
];

export function getDeviceListStats(devices: AssetDevice[]): DeviceListStat[] {
  const total = devices.length;
  const vulnerabilities = devices.reduce(
    (sum, device) => sum + device.vulnerabilityCount,
    0,
  );
  const isolated = devices.filter((device) => device.isolated).length;
  const atRisk = devices.filter(
    (device) => device.status === "at-risk" || device.riskScore >= 70,
  ).length;

  return [
    {
      title: "Vulnerabilities",
      value: String(vulnerabilities),
      delta: -8.2,
      context: "vs last week",
      preferLower: true,
    },
    {
      title: "Isolated",
      value: String(isolated),
      delta: -12.5,
      context: "vs last week",
      preferLower: true,
    },
    {
      title: "Total devices",
      value: String(total),
      delta: 6.2,
      context: "vs last week",
      preferLower: false,
    },
    {
      title: "At risk",
      value: String(atRisk),
      delta: -3.4,
      context: "vs last week",
      preferLower: true,
    },
  ];
}

export function getDevicesByCategory(category: DeviceCategory) {
  return assetDevices.filter((device) => device.category === category);
}
