export type IdentityKind = "user" | "service" | "guest";

export type IdentityStatus = "active" | "disabled" | "locked" | "stale";

export type IdentitySource =
  | "Entra ID"
  | "Okta"
  | "Active Directory"
  | "AWS IAM"
  | "Local";

export type AssetIdentity = {
  id: string;
  displayName: string;
  /** UPN, email, or service principal / client id. */
  principal: string;
  kind: IdentityKind;
  source: IdentitySource;
  status: IdentityStatus;
  department: string;
  owner: string;
  title: string;
  privileged: boolean;
  /** null = not applicable (typical for some service accounts). */
  mfaEnabled: boolean | null;
  avatar?: string;
  lastSeenLabel: string;
  lastSeenValue: number;
  riskScore: number;
  /** Directory / security groups shown in the detail sheet. */
  groups: string[];
  lastPasswordChangeLabel: string;
  signInLocation: string;
  linkedDevices: string[];
  /** Short analyst-facing risk rationale. Empty when nothing noteworthy. */
  notes: string;
};

export const identityKindLabels: Record<IdentityKind, string> = {
  user: "User",
  service: "Service account",
  guest: "Guest",
};

export const identityStatusLabels: Record<IdentityStatus, string> = {
  active: "Active",
  disabled: "Disabled",
  locked: "Locked",
  stale: "Stale",
};

export const identityStatusColors: Record<IdentityStatus, string> = {
  active: "#22c55e",
  disabled: "#71717a",
  locked: "#ef4444",
  stale: "#f59e0b",
};

export type IdentityListStat = {
  title: string;
  value: string;
  delta: number;
  context: string;
  /** When true, a falling trend is healthy (shown in green). */
  preferLower: boolean;
};

type IdentitySeed = Omit<
  AssetIdentity,
  | "privileged"
  | "mfaEnabled"
  | "groups"
  | "lastPasswordChangeLabel"
  | "signInLocation"
  | "linkedDevices"
  | "notes"
> &
  Partial<
    Pick<
      AssetIdentity,
      | "privileged"
      | "mfaEnabled"
      | "groups"
      | "lastPasswordChangeLabel"
      | "signInLocation"
      | "linkedDevices"
      | "notes"
    >
  >;

const defaultGroups: Record<IdentityKind, string[]> = {
  user: ["All Employees", "SSO Users"],
  service: ["Service Principals"],
  guest: ["External Collaborators"],
};

const defaultSignInLocation: Record<IdentityKind, string> = {
  user: "HQ · New York",
  service: "Automation · us-east-1",
  guest: "Remote",
};

const defaultPasswordChange: Record<IdentityKind, string> = {
  user: "38 days ago",
  service: "Rotated 30 days ago",
  guest: "62 days ago",
};

function defineIdentity(seed: IdentitySeed): AssetIdentity {
  return {
    privileged: false,
    mfaEnabled: seed.kind === "service" ? null : true,
    groups: defaultGroups[seed.kind],
    lastPasswordChangeLabel: defaultPasswordChange[seed.kind],
    signInLocation: defaultSignInLocation[seed.kind],
    linkedDevices: [],
    notes: "",
    ...seed,
  };
}

export const assetIdentities: AssetIdentity[] = [
  // Human users (30) — 10 privileged
  defineIdentity({
    id: "id-user-01",
    displayName: "Wendy Darling",
    principal: "wendy.darling@svalbard.ca",
    kind: "user",
    source: "Entra ID",
    status: "active",
    department: "Security",
    owner: "Security",
    title: "SOC Director",
    privileged: true,
    avatar: "/avatars/avatar-1.png",
    lastSeenLabel: "Active now",
    lastSeenValue: 202607241450,
    riskScore: 22,
    groups: ["All Employees", "SOC Leads", "Global Admins"],
    lastPasswordChangeLabel: "12 days ago",
    signInLocation: "HQ · SOC floor",
    linkedDevices: ["WS-SOC-0007", "IPH-EXE-0003"],
  }),
  defineIdentity({
    id: "id-user-02",
    displayName: "John Darling",
    principal: "john.darling@svalbard.ca",
    kind: "user",
    source: "Entra ID",
    status: "active",
    department: "Engineering",
    owner: "Security Engineering",
    title: "Security Engineering Lead",
    privileged: true,
    avatar: "/avatars/avatar-2.png",
    lastSeenLabel: "4 min ago",
    lastSeenValue: 202607241446,
    riskScore: 28,
    groups: ["All Employees", "Detection Engineering", "Cloud Admins"],
    linkedDevices: ["LAP-ENG-0042"],
  }),
  defineIdentity({
    id: "id-user-03",
    displayName: "Peter Pan",
    principal: "peter.pan@svalbard.ca",
    kind: "user",
    source: "Okta",
    status: "active",
    department: "Security",
    owner: "Tier 2 Investigations",
    title: "Tier 2 Analyst",
    avatar: "/avatars/avatar-3.png",
    lastSeenLabel: "12 min ago",
    lastSeenValue: 202607241438,
    riskScore: 14,
    groups: ["All Employees", "SOC Analysts"],
    linkedDevices: ["WS-SOC-0011"],
  }),
  defineIdentity({
    id: "id-user-04",
    displayName: "Tiger Lily",
    principal: "tiger.lily@svalbard.ca",
    kind: "user",
    source: "Entra ID",
    status: "active",
    department: "Security",
    owner: "Incident Response",
    title: "Incident Responder",
    avatar: "/avatars/avatar-4.png",
    lastSeenLabel: "1 hour ago",
    lastSeenValue: 202607241350,
    riskScore: 19,
    groups: ["All Employees", "Incident Response"],
    linkedDevices: ["LAP-IR-0015"],
  }),
  defineIdentity({
    id: "id-user-05",
    displayName: "Tootles",
    principal: "tootles@svalbard.ca",
    kind: "user",
    source: "Okta",
    status: "stale",
    department: "Security",
    owner: "Tier 1 Triage",
    title: "Tier 1 Analyst",
    mfaEnabled: false,
    avatar: "/avatars/avatar-5.png",
    lastSeenLabel: "3 days ago",
    lastSeenValue: 202607211100,
    riskScore: 64,
    lastPasswordChangeLabel: "94 days ago",
    signInLocation: "Remote · Denver",
    notes: "No sign-in for 3 days and MFA unenrolled after device swap.",
  }),
  defineIdentity({
    id: "id-user-06",
    displayName: "Tinker Bell",
    principal: "tinker.bell@svalbard.ca",
    kind: "user",
    source: "Entra ID",
    status: "active",
    department: "Security",
    owner: "Threat Intelligence",
    title: "Threat Intel Analyst",
    avatar: "/avatars/avatar-6.png",
    lastSeenLabel: "26 min ago",
    lastSeenValue: 202607241424,
    riskScore: 16,
    groups: ["All Employees", "Threat Intelligence"],
  }),
  defineIdentity({
    id: "id-user-07",
    displayName: "James Hook",
    principal: "james.hook@svalbard.ca",
    kind: "user",
    source: "Active Directory",
    status: "active",
    department: "Security",
    owner: "Architecture",
    title: "Security Architect",
    privileged: true,
    avatar: "/avatars/avatar-black-1.png",
    lastSeenLabel: "18 min ago",
    lastSeenValue: 202607241432,
    riskScore: 31,
    groups: ["All Employees", "Architecture Board", "Domain Admins"],
  }),
  defineIdentity({
    id: "id-user-08",
    displayName: "George Darling",
    principal: "george.darling@svalbard.ca",
    kind: "user",
    source: "Entra ID",
    status: "active",
    department: "Executive",
    owner: "Executive",
    title: "Chief Information Officer",
    privileged: true,
    avatar: "/avatars/avatar-black-2.png",
    lastSeenLabel: "9 min ago",
    lastSeenValue: 202607241441,
    riskScore: 41,
    groups: ["All Employees", "Executive Team", "Global Admins"],
    signInLocation: "HQ · Floor 5",
    linkedDevices: ["IPH-EXE-0003"],
    notes: "High-value target; conditional access policy enforced.",
  }),
  defineIdentity({
    id: "id-user-09",
    displayName: "First Twin",
    principal: "first.twin@svalbard.ca",
    kind: "user",
    source: "Okta",
    status: "active",
    department: "Operations",
    owner: "Operations",
    title: "IT Operations Manager",
    privileged: true,
    mfaEnabled: false,
    avatar: "/avatars/avatar-black-3.png",
    lastSeenLabel: "2 hours ago",
    lastSeenValue: 202607241250,
    riskScore: 78,
    groups: ["All Employees", "IT Operations", "Helpdesk Admins"],
    lastPasswordChangeLabel: "121 days ago",
    signInLocation: "Field · Austin",
    linkedDevices: ["TAB-OPS-0190"],
    notes: "Privileged account with MFA disabled since device migration.",
  }),
  defineIdentity({
    id: "id-user-10",
    displayName: "Second Twin",
    principal: "second.twin@svalbard.ca",
    kind: "user",
    source: "Entra ID",
    status: "active",
    department: "People",
    owner: "People",
    title: "HR Systems Admin",
    privileged: true,
    avatar: "/avatars/avatar-black-4.png",
    lastSeenLabel: "5 min ago",
    lastSeenValue: 202607241445,
    riskScore: 36,
    groups: ["All Employees", "HRIS Admins"],
    linkedDevices: ["DESK-HR-0088"],
  }),
  defineIdentity({
    id: "id-user-11",
    displayName: "Black Murphy",
    principal: "black.murphy@svalbard.ca",
    kind: "user",
    source: "Okta",
    status: "disabled",
    department: "Sales",
    owner: "Sales",
    title: "Account Executive",
    mfaEnabled: false,
    avatar: "/avatars/avatar-black-5.png",
    lastSeenLabel: "18 hours ago",
    lastSeenValue: 202607232045,
    riskScore: 47,
    signInLocation: "Remote · Chicago",
    notes: "Disabled pending offboarding checklist completion.",
  }),
  defineIdentity({
    id: "id-user-12",
    displayName: "Canary Robb",
    principal: "canary.robb@svalbard.ca",
    kind: "user",
    source: "Entra ID",
    status: "active",
    department: "Product",
    owner: "Product",
    title: "Product Designer",
    avatar: "/avatars/avatar-black-6.png",
    lastSeenLabel: "1 hour ago",
    lastSeenValue: 202607241350,
    riskScore: 12,
    signInLocation: "Remote · SF",
    linkedDevices: ["MBP-DES-0331"],
  }),
  defineIdentity({
    id: "id-user-13",
    displayName: "Mr. Smee",
    principal: "smee@svalbard.ca",
    kind: "user",
    source: "Active Directory",
    status: "active",
    department: "Security",
    owner: "SOC",
    title: "Detection Engineer",
    avatar: "/avatars/avatar-bw-1.png",
    lastSeenLabel: "Just now",
    lastSeenValue: 202607241450,
    riskScore: 11,
    groups: ["All Employees", "Detection Engineering"],
    signInLocation: "HQ · SOC floor",
    linkedDevices: ["WS-SOC-0007"],
  }),
  defineIdentity({
    id: "id-user-14",
    displayName: "Slightly",
    principal: "slightly@svalbard.ca",
    kind: "user",
    source: "Entra ID",
    status: "active",
    department: "Security",
    owner: "Incident Response",
    title: "Forensics Specialist",
    avatar: "/avatars/avatar-black-4.png",
    lastSeenLabel: "38 min ago",
    lastSeenValue: 202607241412,
    riskScore: 18,
    groups: ["All Employees", "Incident Response"],
    linkedDevices: ["LAP-IR-0015"],
  }),
  defineIdentity({
    id: "id-user-15",
    displayName: "Mary Darling",
    principal: "mary.darling@svalbard.ca",
    kind: "user",
    source: "Okta",
    status: "active",
    department: "Security",
    owner: "GRC",
    title: "Compliance Manager",
    privileged: true,
    avatar: "/avatars/avatar-black-5.png",
    lastSeenLabel: "5 hours ago",
    lastSeenValue: 202607240950,
    riskScore: 15,
    groups: ["All Employees", "GRC"],
  }),
  defineIdentity({
    id: "id-user-16",
    displayName: "Nibs",
    principal: "nibs@svalbard.ca",
    kind: "user",
    source: "Entra ID",
    status: "stale",
    department: "Security",
    owner: "Vulnerability Management",
    title: "Vulnerability Analyst",
    mfaEnabled: false,
    avatar: "/avatars/avatar-black-6.png",
    lastSeenLabel: "6 days ago",
    lastSeenValue: 202607181100,
    riskScore: 52,
    groups: ["All Employees", "Vuln Management"],
  }),
  defineIdentity({
    id: "id-user-17",
    displayName: "Curly",
    principal: "curly@svalbard.ca",
    kind: "user",
    source: "Active Directory",
    status: "active",
    department: "Security",
    owner: "Detection Engineering",
    title: "Automation Engineer",
    avatar: "/avatars/avatar-bw-1.png",
    lastSeenLabel: "9 min ago",
    lastSeenValue: 202607241441,
    riskScore: 14,
    groups: ["All Employees", "Detection Engineering", "Incident Response"],
  }),
  defineIdentity({
    id: "id-user-18",
    displayName: "Michael Darling",
    principal: "michael.darling@svalbard.ca",
    kind: "user",
    source: "Entra ID",
    status: "active",
    department: "Security",
    owner: "GRC",
    title: "GRC Auditor",
    avatar: "/avatars/avatar-bw-2.png",
    lastSeenLabel: "3 hours ago",
    lastSeenValue: 202607241150,
    riskScore: 12,
    groups: ["All Employees", "GRC"],
  }),
  defineIdentity({
    id: "id-user-19",
    displayName: "Cecco",
    principal: "cecco@svalbard.ca",
    kind: "user",
    source: "Entra ID",
    status: "active",
    department: "Security",
    owner: "Cloud Security",
    title: "Cloud Security Engineer",
    avatar: "/avatars/avatar-bw-3.png",
    lastSeenLabel: "51 min ago",
    lastSeenValue: 202607241359,
    riskScore: 19,
    groups: ["All Employees", "Cloud Security"],
    linkedDevices: ["LAP-ENG-0077"],
  }),
  defineIdentity({
    id: "id-user-20",
    displayName: "Bill Jukes",
    principal: "bill.jukes@svalbard.ca",
    kind: "user",
    source: "Okta",
    status: "stale",
    department: "Security",
    owner: "Tier 1 Triage",
    title: "Tier 1 Analyst",
    mfaEnabled: false,
    avatar: "/avatars/avatar-bw-4.png",
    lastSeenLabel: "4 days ago",
    lastSeenValue: 202607201100,
    riskScore: 48,
    groups: ["All Employees", "SOC Analysts", "Threat Intelligence"],
  }),
  defineIdentity({
    id: "id-user-21",
    displayName: "Nana",
    principal: "nana@partners.svalbard.ca",
    kind: "user",
    source: "Entra ID",
    status: "disabled",
    department: "Partners",
    owner: "MSSP",
    title: "MSSP Support Partner",
    mfaEnabled: false,
    avatar: "/avatars/avatar-black-3.png",
    lastSeenLabel: "2 weeks ago",
    lastSeenValue: 202607101200,
    riskScore: 27,
    groups: ["External Collaborators", "MSSP Viewers"],
    notes: "Partner viewer seat; access limited to Tier 1 dashboards.",
  }),
  defineIdentity({
    id: "id-user-22",
    displayName: "Liza",
    principal: "liza@svalbard.ca",
    kind: "user",
    source: "Entra ID",
    status: "active",
    department: "Finance",
    owner: "Finance",
    title: "Controller",
    avatar: "/avatars/avatar-bw-2.png",
    lastSeenLabel: "2 min ago",
    lastSeenValue: 202607241448,
    riskScore: 18,
    groups: ["All Employees", "Finance Approvers"],
    linkedDevices: ["LAP-FIN-0142"],
  }),
  defineIdentity({
    id: "id-user-23",
    displayName: "Gentleman Starkey",
    principal: "gentleman.starkey@svalbard.ca",
    kind: "user",
    source: "Entra ID",
    status: "active",
    department: "Security",
    owner: "Identity",
    title: "IAM Administrator",
    privileged: true,
    avatar: "/avatars/avatar-5.png",
    lastSeenLabel: "3 min ago",
    lastSeenValue: 202607241447,
    riskScore: 33,
    groups: ["All Employees", "Identity Team", "Global Admins"],
    lastPasswordChangeLabel: "8 days ago",
  }),
  defineIdentity({
    id: "id-user-24",
    displayName: "Alf Mason",
    principal: "alf.mason.crew@svalbard.ca",
    kind: "user",
    source: "Okta",
    status: "disabled",
    department: "Sales",
    owner: "Sales",
    title: "Account Executive",
    mfaEnabled: false,
    avatar: "/avatars/avatar-black-5.png",
    lastSeenLabel: "18 hours ago",
    lastSeenValue: 202607232045,
    riskScore: 47,
    signInLocation: "Remote · Chicago",
    notes: "Disabled pending offboarding checklist completion.",
  }),
  defineIdentity({
    id: "id-user-25",
    displayName: "Neverbird",
    principal: "neverbird@svalbard.ca",
    kind: "user",
    source: "Active Directory",
    status: "active",
    department: "Infrastructure",
    owner: "IT Ops",
    title: "Database Administrator",
    privileged: true,
    mfaEnabled: false,
    avatar: "/avatars/avatar-black-3.png",
    lastSeenLabel: "1 hour ago",
    lastSeenValue: 202607241345,
    riskScore: 74,
    groups: ["All Employees", "Database Admins"],
    lastPasswordChangeLabel: "156 days ago",
    signInLocation: "DC · Rack A04",
    notes: "DBA with direct production access and no MFA enrollment.",
  }),
  defineIdentity({
    id: "id-user-26",
    displayName: "Skylights",
    principal: "skylights.crew@svalbard.ca",
    kind: "user",
    source: "Entra ID",
    status: "active",
    department: "Finance",
    owner: "Finance",
    title: "Payroll Specialist",
    avatar: "/avatars/avatar-black-4.png",
    lastSeenLabel: "22 min ago",
    lastSeenValue: 202607241428,
    riskScore: 21,
    groups: ["All Employees", "Payroll Access"],
  }),
  defineIdentity({
    id: "id-user-27",
    displayName: "Cookson",
    principal: "cookson.crew@svalbard.ca",
    kind: "user",
    source: "Okta",
    status: "active",
    department: "Engineering",
    owner: "QA",
    title: "QA Engineer",
    avatar: "/avatars/avatar-black-5.png",
    lastSeenLabel: "2 hours ago",
    lastSeenValue: 202607241245,
    riskScore: 14,
  }),
  defineIdentity({
    id: "id-user-28",
    displayName: "Jolly Roger",
    principal: "jolly.roger@svalbard.ca",
    kind: "user",
    source: "Entra ID",
    status: "disabled",
    department: "Marketing",
    owner: "Marketing",
    title: "Content Strategist",
    mfaEnabled: false,
    avatar: "/avatars/avatar-black-6.png",
    lastSeenLabel: "1 month ago",
    lastSeenValue: 202606241200,
    riskScore: 35,
    notes: "Departed employee; mailbox converted to shared.",
  }),
  defineIdentity({
    id: "id-user-29",
    displayName: "Crocodile",
    principal: "crocodile@svalbard.ca",
    kind: "user",
    source: "Okta",
    status: "active",
    department: "Sales",
    owner: "Sales",
    title: "Sales Engineer",
    avatar: "/avatars/avatar-bw-1.png",
    lastSeenLabel: "17 min ago",
    lastSeenValue: 202607241433,
    riskScore: 18,
    signInLocation: "Remote · Toronto",
  }),
  defineIdentity({
    id: "id-user-30",
    displayName: "Lost Boy",
    principal: "lost.boy@svalbard.ca",
    kind: "user",
    source: "Entra ID",
    status: "active",
    department: "Legal",
    owner: "Legal",
    title: "Contracts Manager",
    avatar: "/avatars/avatar-bw-2.png",
    lastSeenLabel: "1 hour ago",
    lastSeenValue: 202607241340,
    riskScore: 12,
  }),

  // Service accounts (16) — 5 privileged
  defineIdentity({
    id: "id-svc-01",
    displayName: "SIEM Ingest",
    principal: "svc-siem-ingest@svalbard.ca",
    kind: "service",
    source: "Entra ID",
    status: "active",
    department: "Security",
    owner: "Detection Engineering",
    title: "Log shipping principal",
    lastSeenLabel: "1 min ago",
    lastSeenValue: 202607241449,
    riskScore: 24,
    groups: ["Service Principals", "Log Writers"],
    lastPasswordChangeLabel: "Rotated 14 days ago",
    linkedDevices: ["srv-siem-02"],
  }),
  defineIdentity({
    id: "id-svc-02",
    displayName: "Backup Orchestrator",
    principal: "svc-backup-orch@svalbard.ca",
    kind: "service",
    source: "Active Directory",
    status: "active",
    department: "Infrastructure",
    owner: "IT Ops",
    title: "Scheduled backup runner",
    privileged: true,
    lastSeenLabel: "3 min ago",
    lastSeenValue: 202607241447,
    riskScore: 58,
    groups: ["Service Principals", "Backup Operators"],
    lastPasswordChangeLabel: "Rotated 89 days ago",
    signInLocation: "DC · Rack C02",
    linkedDevices: ["srv-bkp-03"],
    notes: "Credential rotation overdue per 60-day policy.",
  }),
  defineIdentity({
    id: "id-svc-03",
    displayName: "CI Deploy Bot",
    principal: "app:ci-deploy-bot",
    kind: "service",
    source: "AWS IAM",
    status: "active",
    department: "Engineering",
    owner: "DevOps",
    title: "Pipeline deploy role",
    privileged: true,
    lastSeenLabel: "8 min ago",
    lastSeenValue: 202607241442,
    riskScore: 66,
    groups: ["Service Principals", "Deploy Roles"],
    lastPasswordChangeLabel: "Key rotated 45 days ago",
    signInLocation: "GCP · us-central1",
    linkedDevices: ["srv-ci-07"],
    notes: "Broad deploy permissions; scoping review in backlog.",
  }),
  defineIdentity({
    id: "id-svc-04",
    displayName: "Okta SCIM Sync",
    principal: "svc-okta-scim@svalbard.ca",
    kind: "service",
    source: "Okta",
    status: "active",
    department: "Security",
    owner: "Identity",
    title: "Directory provisioning",
    privileged: true,
    lastSeenLabel: "Just now",
    lastSeenValue: 202607241450,
    riskScore: 44,
    groups: ["Service Principals", "Provisioning"],
    lastPasswordChangeLabel: "Token rotated 7 days ago",
  }),
  defineIdentity({
    id: "id-svc-05",
    displayName: "Monitoring Agent",
    principal: "svc-monitor@svalbard.ca",
    kind: "service",
    source: "Local",
    status: "active",
    department: "Infrastructure",
    owner: "SRE",
    title: "Host telemetry collector",
    lastSeenLabel: "2 min ago",
    lastSeenValue: 202607241448,
    riskScore: 21,
  }),
  defineIdentity({
    id: "id-svc-06",
    displayName: "Payroll Integration",
    principal: "svc-payroll-api@svalbard.ca",
    kind: "service",
    source: "Entra ID",
    status: "active",
    department: "Finance",
    owner: "Finance Systems",
    title: "HRIS connector",
    lastSeenLabel: "14 min ago",
    lastSeenValue: 202607241436,
    riskScore: 39,
    groups: ["Service Principals", "HRIS Access"],
  }),
  defineIdentity({
    id: "id-svc-07",
    displayName: "Vulnerability Scanner",
    principal: "svc-vuln-scan@svalbard.ca",
    kind: "service",
    source: "Active Directory",
    status: "active",
    department: "Security",
    owner: "Vulnerability Management",
    title: "Network scan principal",
    privileged: true,
    lastSeenLabel: "22 min ago",
    lastSeenValue: 202607241428,
    riskScore: 61,
    groups: ["Service Principals", "Scan Accounts", "Local Admin (broad)"],
    notes: "Holds local admin on scanned hosts; candidate for JIT elevation.",
  }),
  defineIdentity({
    id: "id-svc-08",
    displayName: "Slack Notifier",
    principal: "svc-slack-notify@svalbard.ca",
    kind: "service",
    source: "Okta",
    status: "stale",
    department: "Security",
    owner: "SOC",
    title: "Alert fan-out bot",
    lastSeenLabel: "9 days ago",
    lastSeenValue: 202607151000,
    riskScore: 52,
    lastPasswordChangeLabel: "Token rotated 190 days ago",
    notes: "Unused since alert routing moved to the new pipeline.",
  }),
  defineIdentity({
    id: "id-svc-09",
    displayName: "Warehouse ETL",
    principal: "svc-wh-etl@svalbard.ca",
    kind: "service",
    source: "AWS IAM",
    status: "active",
    department: "Data",
    owner: "Data Platform",
    title: "Nightly warehouse load",
    lastSeenLabel: "6 hours ago",
    lastSeenValue: 202607240850,
    riskScore: 33,
  }),
  defineIdentity({
    id: "id-svc-10",
    displayName: "MDM Enrollment",
    principal: "svc-mdm-enroll@svalbard.ca",
    kind: "service",
    source: "Entra ID",
    status: "active",
    department: "Operations",
    owner: "IT Ops",
    title: "Device enrollment API",
    lastSeenLabel: "11 min ago",
    lastSeenValue: 202607241439,
    riskScore: 27,
  }),
  defineIdentity({
    id: "id-svc-11",
    displayName: "Legacy Print Spooler",
    principal: "svc-print-legacy",
    kind: "service",
    source: "Local",
    status: "disabled",
    department: "Operations",
    owner: "IT Ops",
    title: "Deprecated print service",
    lastSeenLabel: "Never",
    lastSeenValue: 0,
    riskScore: 48,
    lastPasswordChangeLabel: "Unknown",
    notes: "Legacy local account kept for audit trail; deletion pending.",
  }),
  defineIdentity({
    id: "id-svc-12",
    displayName: "Threat Intel Feed",
    principal: "svc-ti-feed@svalbard.ca",
    kind: "service",
    source: "Okta",
    status: "active",
    department: "Security",
    owner: "Threat Intelligence",
    title: "IOC ingestion principal",
    lastSeenLabel: "7 min ago",
    lastSeenValue: 202607241443,
    riskScore: 29,
  }),
  defineIdentity({
    id: "id-svc-13",
    displayName: "GitHub Actions Runner",
    principal: "app:gh-actions-runner",
    kind: "service",
    source: "AWS IAM",
    status: "active",
    department: "Engineering",
    owner: "DevOps",
    title: "CI workflow role",
    lastSeenLabel: "5 min ago",
    lastSeenValue: 202607241445,
    riskScore: 36,
    groups: ["Service Principals", "CI Roles"],
    lastPasswordChangeLabel: "OIDC federated",
  }),
  defineIdentity({
    id: "id-svc-14",
    displayName: "Email Gateway",
    principal: "svc-mail-gateway@svalbard.ca",
    kind: "service",
    source: "Entra ID",
    status: "active",
    department: "Infrastructure",
    owner: "IT Ops",
    title: "Mail relay principal",
    lastSeenLabel: "1 min ago",
    lastSeenValue: 202607241449,
    riskScore: 25,
  }),
  defineIdentity({
    id: "id-svc-15",
    displayName: "PAM Vault Sync",
    principal: "svc-pam-vault@svalbard.ca",
    kind: "service",
    source: "Active Directory",
    status: "active",
    department: "Security",
    owner: "Identity",
    title: "Privileged credential vault",
    privileged: true,
    lastSeenLabel: "9 min ago",
    lastSeenValue: 202607241441,
    riskScore: 49,
    groups: ["Service Principals", "Vault Operators"],
    lastPasswordChangeLabel: "Rotated 3 days ago",
  }),
  defineIdentity({
    id: "id-svc-16",
    displayName: "Analytics Exporter",
    principal: "svc-analytics-export@svalbard.ca",
    kind: "service",
    source: "Okta",
    status: "active",
    department: "Data",
    owner: "Data Platform",
    title: "BI export principal",
    lastSeenLabel: "42 min ago",
    lastSeenValue: 202607241408,
    riskScore: 23,
  }),

  // Guest users (16)
  defineIdentity({
    id: "id-guest-01",
    displayName: "Jane",
    principal: "kara.nguyen@vendor-secure.io",
    kind: "guest",
    source: "Entra ID",
    status: "active",
    department: "Contractors",
    owner: "Vendor Access",
    title: "External pen tester",
    avatar: "/avatars/avatar-3.png",
    lastSeenLabel: "35 min ago",
    lastSeenValue: 202607241415,
    riskScore: 42,
    groups: ["External Collaborators", "Pen Test Scope"],
    signInLocation: "Remote · VPN",
    notes: "Engagement ends Aug 15; access auto-expires.",
  }),
  defineIdentity({
    id: "id-guest-02",
    displayName: "Rabbit",
    principal: "diego.morales@partner-cloud.com",
    kind: "guest",
    source: "Okta",
    status: "active",
    department: "Contractors",
    owner: "Partner Success",
    title: "Integration partner",
    avatar: "/avatars/avatar-4.png",
    lastSeenLabel: "2 hours ago",
    lastSeenValue: 202607241250,
    riskScore: 34,
  }),
  defineIdentity({
    id: "id-guest-03",
    displayName: "Cannonball",
    principal: "amelia.brooks@audit-firm.com",
    kind: "guest",
    source: "Entra ID",
    status: "active",
    department: "Compliance",
    owner: "GRC",
    title: "External auditor",
    avatar: "/avatars/avatar-5.png",
    lastSeenLabel: "Yesterday",
    lastSeenValue: 202607231600,
    riskScore: 38,
    groups: ["External Collaborators", "Audit Read-only"],
  }),
  defineIdentity({
    id: "id-guest-04",
    displayName: "Wibbles",
    principal: "leo.andersson@msp-north.eu",
    kind: "guest",
    source: "Okta",
    status: "stale",
    department: "Contractors",
    owner: "IT Ops",
    title: "Managed service engineer",
    mfaEnabled: false,
    avatar: "/avatars/avatar-6.png",
    lastSeenLabel: "16 days ago",
    lastSeenValue: 202607081200,
    riskScore: 73,
    signInLocation: "Remote · Stockholm",
    notes: "MSP contract renewal unclear; access review overdue.",
  }),
  defineIdentity({
    id: "id-guest-05",
    displayName: "Fairy",
    principal: "sofia.berg@design-studio.co",
    kind: "guest",
    source: "Entra ID",
    status: "active",
    department: "Product",
    owner: "Product",
    title: "Contract designer",
    avatar: "/avatars/avatar-black-1.png",
    lastSeenLabel: "4 hours ago",
    lastSeenValue: 202607241050,
    riskScore: 26,
  }),
  defineIdentity({
    id: "id-guest-06",
    displayName: "Noodler",
    principal: "marcus.cole@legal-counsel.com",
    kind: "guest",
    source: "Entra ID",
    status: "disabled",
    department: "Legal",
    owner: "Legal",
    title: "Outside counsel",
    mfaEnabled: false,
    avatar: "/avatars/avatar-black-2.png",
    lastSeenLabel: "2 months ago",
    lastSeenValue: 202605201000,
    riskScore: 55,
    notes: "Matter closed; retained for records only.",
  }),
  defineIdentity({
    id: "id-guest-07",
    displayName: "Boatswain",
    principal: "yuki.tanaka@cloud-partner.jp",
    kind: "guest",
    source: "Okta",
    status: "active",
    department: "Engineering",
    owner: "Platform",
    title: "Cloud partner engineer",
    avatar: "/avatars/avatar-black-3.png",
    lastSeenLabel: "50 min ago",
    lastSeenValue: 202607241400,
    riskScore: 31,
    signInLocation: "Remote · Tokyo",
  }),
  defineIdentity({
    id: "id-guest-08",
    displayName: "Mermaid",
    principal: "ibrahim.diallo@security-mssp.com",
    kind: "guest",
    source: "Entra ID",
    status: "active",
    department: "Security",
    owner: "SOC",
    title: "MSSP analyst",
    avatar: "/avatars/avatar-black-4.png",
    lastSeenLabel: "15 min ago",
    lastSeenValue: 202607241435,
    riskScore: 29,
    groups: ["External Collaborators", "SOC Read-only"],
  }),
  defineIdentity({
    id: "id-guest-09",
    displayName: "Alf Mason",
    principal: "nina.petrov@temp-staff.io",
    kind: "guest",
    source: "Okta",
    status: "locked",
    department: "Contractors",
    owner: "People",
    title: "Temporary contractor",
    mfaEnabled: false,
    avatar: "/avatars/avatar-black-5.png",
    lastSeenLabel: "5 days ago",
    lastSeenValue: 202607191200,
    riskScore: 68,
    notes: "Locked after repeated password failures; sponsor notified.",
  }),
  defineIdentity({
    id: "id-guest-10",
    displayName: "Robert Mullins",
    principal: "james.whitfield@board-advisors.com",
    kind: "guest",
    source: "Entra ID",
    status: "active",
    department: "Executive",
    owner: "Executive",
    title: "Board advisor",
    avatar: "/avatars/avatar-black-6.png",
    lastSeenLabel: "3 days ago",
    lastSeenValue: 202607211400,
    riskScore: 45,
    groups: ["External Collaborators", "Board Portal"],
  }),
  defineIdentity({
    id: "id-guest-11",
    displayName: "Neverland Scout",
    principal: "fatima.alhassan@research-lab.edu",
    kind: "guest",
    source: "Okta",
    status: "active",
    department: "Security",
    owner: "Threat Intelligence",
    title: "Research collaborator",
    avatar: "/avatars/avatar-bw-1.png",
    lastSeenLabel: "1 day ago",
    lastSeenValue: 202607231450,
    riskScore: 37,
  }),
  defineIdentity({
    id: "id-guest-12",
    displayName: "Chay Turley",
    principal: "ethan.brooks@temp-dev.co",
    kind: "guest",
    source: "Entra ID",
    status: "stale",
    department: "Engineering",
    owner: "Engineering",
    title: "Contract developer",
    mfaEnabled: false,
    avatar: "/avatars/avatar-bw-2.png",
    lastSeenLabel: "21 days ago",
    lastSeenValue: 202607031000,
    riskScore: 76,
    lastPasswordChangeLabel: "148 days ago",
    notes: "Contract ended; deprovisioning ticket open with sponsor.",
  }),
  defineIdentity({
    id: "id-guest-13",
    displayName: "Starkey Mate",
    principal: "clara.dubois@translate-pro.fr",
    kind: "guest",
    source: "Entra ID",
    status: "active",
    department: "Marketing",
    owner: "Marketing",
    title: "Localization vendor",
    avatar: "/avatars/avatar-bw-3.png",
    lastSeenLabel: "5 hours ago",
    lastSeenValue: 202607240950,
    riskScore: 24,
  }),
  defineIdentity({
    id: "id-guest-14",
    displayName: "Mullins Mate",
    principal: "raj.malhotra@consulting-grp.com",
    kind: "guest",
    source: "Okta",
    status: "active",
    department: "Finance",
    owner: "Finance",
    title: "ERP consultant",
    avatar: "/avatars/avatar-bw-4.png",
    lastSeenLabel: "2 hours ago",
    lastSeenValue: 202607241245,
    riskScore: 32,
    groups: ["External Collaborators", "ERP Project"],
  }),
  defineIdentity({
    id: "id-guest-15",
    displayName: "Hook Cabin Boy",
    principal: "maris.quell@recruiting-partners.com",
    kind: "guest",
    source: "Entra ID",
    status: "active",
    department: "People",
    owner: "People",
    title: "Recruiting partner",
    avatar: "/avatars/avatar-1.png",
    lastSeenLabel: "1 hour ago",
    lastSeenValue: 202607241344,
    riskScore: 27,
  }),
  defineIdentity({
    id: "id-guest-16",
    displayName: "Smee Mate",
    principal: "viktor.hansen@insurer-audit.dk",
    kind: "guest",
    source: "Okta",
    status: "active",
    department: "Compliance",
    owner: "GRC",
    title: "Insurance assessor",
    avatar: "/avatars/avatar-2.png",
    lastSeenLabel: "Yesterday",
    lastSeenValue: 202607231120,
    riskScore: 30,
  }),
];

export function getIdentityInitials(name: string) {
  return name
    .split(/\s+/)
    .filter(Boolean)
    .slice(0, 2)
    .map((part) => part[0]?.toUpperCase() ?? "")
    .join("");
}

export function isRiskIdentity(identity: AssetIdentity) {
  if (identity.riskScore >= 70) {
    return true;
  }

  if (identity.status === "locked" || identity.status === "stale") {
    return true;
  }

  if (identity.privileged && identity.mfaEnabled === false) {
    return true;
  }

  return false;
}

export type IdentityAttentionKey =
  | "privileged-mfa-gap"
  | "dormant-privileged"
  | "guest-mfa-off";

export type IdentityAttentionFilter = {
  label: string;
  description: string;
  /** Tab that best scopes the results when the chip is activated. */
  tab: "all" | "service" | "privileged" | "guest";
  matches: (identity: AssetIdentity) => boolean;
};

export const identityAttentionFilters: Record<
  IdentityAttentionKey,
  IdentityAttentionFilter
> = {
  "privileged-mfa-gap": {
    label: "Privileged without MFA",
    description: "Elevated access with no second factor enrolled.",
    tab: "privileged",
    matches: (identity) =>
      identity.privileged && identity.mfaEnabled === false,
  },
  "dormant-privileged": {
    label: "Dormant privileged",
    description: "Privileged accounts that are stale or locked.",
    tab: "privileged",
    matches: (identity) =>
      identity.privileged &&
      (identity.status === "stale" || identity.status === "locked"),
  },
  "guest-mfa-off": {
    label: "Guests without MFA",
    description: "External identities with MFA disabled.",
    tab: "guest",
    matches: (identity) =>
      identity.kind === "guest" && identity.mfaEnabled === false,
  },
};

export function getIdentityListStats(
  identities: AssetIdentity[],
): IdentityListStat[] {
  const total = identities.length;
  const privileged = identities.filter((identity) => identity.privileged).length;
  const mfaGaps = identities.filter(
    (identity) => identity.mfaEnabled === false,
  ).length;
  const atRisk = identities.filter(isRiskIdentity).length;

  return [
    {
      title: "Total identities",
      value: String(total),
      delta: 4.1,
      context: "vs last week",
      preferLower: false,
    },
    {
      title: "Privileged",
      value: String(privileged),
      delta: 1.8,
      context: "vs last week",
      preferLower: true,
    },
    {
      title: "MFA gaps",
      value: String(mfaGaps),
      delta: -6.4,
      context: "vs last week",
      preferLower: true,
    },
    {
      title: "At risk",
      value: String(atRisk),
      delta: -2.7,
      context: "vs last week",
      preferLower: true,
    },
  ];
}

export function getIdentitiesByTab(
  identities: AssetIdentity[],
  tab: "all" | "service" | "privileged" | "guest",
) {
  switch (tab) {
    case "service":
      return identities.filter((identity) => identity.kind === "service");
    case "privileged":
      return identities.filter((identity) => identity.privileged);
    case "guest":
      return identities.filter((identity) => identity.kind === "guest");
    default:
      return identities;
  }
}
